### ISSUE TITLE
获取AccessToken时的String format错误

### ISSUE THREAD

**Issue by 79774911** [yuxiaochou/OpenConnectSDK#1]
var url = string.Format("https://graph.qq.com/oauth2.0/token?client_id={0}&client_secret={1}&code={2}&grant_type={3}}&redirect_uri={4}", appId, secret, code, grantType, HttpUtility.UrlEncode(redirectUrl));

{3}}多半个}。

**Comment by yuxiaochou** [comment]
Fix it. Thank you for your feedback, also updated on nuget.org. 还请多多测试和反馈。

**Comment by 79774911** [comment]
wonderful!
